#!/bin/zsh

cd $HOME

ssh-keyscan github.com >> ~/.ssh/known_hosts

repo_url=$(/usr/bin/git --git-dir=$HOME/.dotfiles/.git remote get-url origin)
git clone $repo_url --bare $HOME/.dotfiles/repo -b dotfiles
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/repo --work-tree=$HOME'

touch /home/$USERNAME/.persistent/.z && ln -s /home/$USERNAME/.persistent/.z /home/$USERNAME/.z
mkdir -p /home/$USERNAME/.persistent/.local
mkdir -p /home/$USERNAME/.persistent/.config
mkdir -p /home/$USERNAME/.persistent/.docker
ln -fs /home/$USERNAME/.persistent/.docker /home/$USERNAME/.docker

[ -d /home/$USERNAME/.oh-my-zsh ] && echo "oh-my-zsh is already there" || sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

mkdir -p .config-backup && dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}

dotfiles checkout
dotfiles submodule update --init
dotfiles config --local status.showUntrackedFiles no

cd /tmp

mkdir exa
curl -L -o exa/exa.zip https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip
cd /tmp/exa
unzip exa.zip
sudo mv bin/exa /usr/local/bin/exa
cd /tmp
rm -rf /tmp/exa

curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | SHELL=zsh zsh
