#!/bin/zsh

cd $HOME

repo_url=$(/usr/bin/git --git-dir=$HOME/.dotfiles/.git remote get-url origin)
git clone $repo_url --bare $HOME/.dotfiles/repo -b dotfiles
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/repo --work-tree=$HOME'

touch /home/$USERNAME/.persistent/.z && ln -s /home/$USERNAME/.persistent/.z /home/$USERNAME/.z
mkdir -p /home/$USERNAME/.persistent/.local
mkdir -p /home/$USERNAME/.persistent/.config
mkdir -p /home/$USERNAME/.persistent/.docker
ln -fs /home/$USERNAME/.persistent/.docker /home/$USERNAME/.docker

mkdir -p .config-backup && dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}

dotfiles checkout
dotfiles submodule update --init
dotfiles config --local status.showUntrackedFiles no

cd /tmp

curl -L -O https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
unzip exa-linux-x86_64-0.9.0.zip
sudo mv exa-linux-x86_64 /usr/local/bin/exa

curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | SHELL=zsh zsh
